/** @type {import('tailwindcss').Config} */
module.exports = {
    content: ["./src/**/*.{html,js}"],
    darkMode: "class",
    plugins: [],
    theme: {
        extend: {
            colors: {
                surface: "#fcf9f8",
                "primary-fixed": "#fde400",
                "on-tertiary-fixed-variant": "#00504c",
                error: "#ba1a1a",
                "on-primary-fixed": "#201c00",
                "surface-variant": "#e5e2e1",
                "surface-container-low": "#f6f3f2",
                "primary-fixed-dim": "#dec800",
                "on-primary-fixed-variant": "#504700",
                outline: "#7c775f",
                "tertiary-fixed-dim": "#5dd9d0",
                tertiary: "#006a65",
                "on-primary-container": "#726600",
                "tertiary-fixed": "#7cf6ec",
                "on-secondary-fixed": "#410006",
                "tertiary-container": "#7ef8ee",
                "surface-container-lowest": "#ffffff",
                "secondary-container": "#ff6b6b",
                "inverse-primary": "#dec800",
                "surface-container-high": "#ebe7e7",
                primary: "#6a5f00",
                "on-surface-variant": "#4b4731",
                "surface-bright": "#fcf9f8",
                "error-container": "#ffdad6",
                "on-tertiary": "#ffffff",
                "on-secondary-fixed-variant": "#8c1520",
                "on-error-container": "#93000a",
                "on-background": "#1c1b1b",
                "inverse-surface": "#313030",
                "on-surface": "#1c1b1b",
                "on-tertiary-container": "#00726c",
                "surface-container-highest": "#e5e2e1",
                "secondary-fixed-dim": "#ffb3b0",
                "surface-container": "#f0edec",
                secondary: "#ae2f34",
                "inverse-on-surface": "#f3f0ef",
                "secondary-fixed": "#ffdad8",
                background: "#fcf9f8",
                "on-error": "#ffffff",
                "on-secondary": "#ffffff",
                "on-secondary-container": "#6d0010",
                "primary-container": "#ffe600",
                "outline-variant": "#cdc7aa",
                "surface-tint": "#6a5f00",
                "on-primary": "#ffffff",
                "on-tertiary-fixed": "#00201e",
                "surface-dim": "#dcd9d9",
            },
            borderRadius: {
                DEFAULT: "0.125rem",
                lg: "0.25rem",
                xl: "0.5rem",
                full: "0.75rem",
            },
            spacing: {
                "space-xxs": "0.25rem",
                "space-2xl": "3rem",
                "space-4xl": "6rem",
                "space-md": "1rem",
                "space-lg": "1.5rem",
                "space-xl": "2rem",
                "gutter-mobile": "1rem",
                "container-max": "85rem",
                "gutter-desktop": "2rem",
                "space-xs": "0.5rem",
                "space-sm": "0.75rem",
                "space-3xl": "4.5rem",
            },
            fontFamily: {
                "display-hero-mobile": ["Space Grotesk"],
                "label-lg": ["Space Grotesk"],
                "display-hero": ["Space Grotesk"],
                "body-md": ["Hanken Grotesk"],
                "body-sm": ["Hanken Grotesk"],
                "label-sm": ["Space Grotesk"],
                "body-lg": ["Hanken Grotesk"],
                "headline-md": ["Space Grotesk"],
                "headline-sm": ["Space Grotesk"],
                "headline-lg-mobile": ["Space Grotesk"],
                "title-lg": ["Space Grotesk"],
                "headline-lg": ["Space Grotesk"],
            },
            fontSize: {
                "display-hero-mobile": [
                    "40px",
                    {
                        lineHeight: "48px",
                        letterSpacing: "-0.02em",
                        fontWeight: "800",
                    },
                ],
                "label-lg": [
                    "15px",
                    {
                        lineHeight: "20px",
                        letterSpacing: "0.04em",
                        fontWeight: "700",
                    },
                ],
                "display-hero": [
                    "64px",
                    {
                        lineHeight: "72px",
                        letterSpacing: "-0.03em",
                        fontWeight: "800",
                    },
                ],
                "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
                "body-sm": ["14px", { lineHeight: "20px", fontWeight: "500" }],
                "label-sm": [
                    "12px",
                    {
                        lineHeight: "16px",
                        letterSpacing: "0.06em",
                        fontWeight: "700",
                    },
                ],
                "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
                "headline-md": [
                    "28px",
                    {
                        lineHeight: "36px",
                        letterSpacing: "-0.01em",
                        fontWeight: "700",
                    },
                ],
                "headline-sm": [
                    "22px",
                    { lineHeight: "28px", fontWeight: "700" },
                ],
                "headline-lg-mobile": [
                    "32px",
                    {
                        lineHeight: "38px",
                        letterSpacing: "-0.01em",
                        fontWeight: "700",
                    },
                ],
                "title-lg": ["18px", { lineHeight: "24px", fontWeight: "700" }],
                "headline-lg": [
                    "44px",
                    {
                        lineHeight: "52px",
                        letterSpacing: "-0.02em",
                        fontWeight: "700",
                    },
                ],
            },
        },
    }
}
